# 

In [1]:
import pandas as pd
import numpy as np

d =np.array([1,2,3,4,5])
print(d)
d1=pd.series(d)
print(d1)

[1 2 3 4 5]


AttributeError: module 'pandas' has no attribute 'series'

In [2]:
import pandas as pd
import numpy as np

d =np.array([1,2,3,4,5])
print(d)

[1 2 3 4 5]


In [3]:
import pandas as pd
import numpy as np

d =np.array([1,2,3,4,5])
print(d)
d1=pd.Series(d)
print(d1)

[1 2 3 4 5]
0    1
1    2
2    3
3    4
4    5
dtype: int64


In [4]:
import pandas as pd
import numpy as np

# Step 1: Load the dataset
df = pd.read_csv("Titanic-Dataset.csv")

# Step 2: Preview the data
print("First few rows of the dataset:")
print(df.head())

# Step 3: Check for missing values
print("Missing values per column:")
print(df.isnull().sum())

# Step 4: Descriptive statistics
print("Summary statistics:")
print(df.describe(include="all"))

# Step 5: Check dimensions
print("Shape of the dataset:", df.shape)

# Step 6: Check and update data types
print("Data types before conversion:")
print(df.dtypes)

# Convert 'Survived' to category
df['Survived'] = df['Survived'].astype('category')
print("Data types after conversion:")
print(df.dtypes)

# Step 7: Encode categorical variables
df = pd.get_dummies(df, columns=['Sex'], drop_first=True)
print("Data after encoding:")
print(df.head())


FileNotFoundError: [Errno 2] No such file or directory: 'Titanic-Dataset.csv'

In [5]:
 import pandas as pd
import numpy as np

# Step 1: Load the dataset
df = pd.read_csv("Titanic-Dataset.csv")

# Step 2: Preview the data
print("First few rows of the dataset:")
print(df.head())

# Step 3: Check for missing values
print("Missing values per column:")
print(df.isnull().sum())

# Step 4: Descriptive statistics
print("Summary statistics:")
print(df.describe(include="all"))

# Step 5: Check dimensions
print("Shape of the dataset:", df.shape)

# Step 6: Check and update data types
print("Data types before conversion:")
print(df.dtypes)

# Convert 'Survived' to category
df['Survived'] = df['Survived'].astype('category')
print("Data types after conversion:")
print(df.dtypes)

# Step 7: Encode categorical variables
df = pd.get_dummies(df, columns=['Sex'], drop_first=True)
print("Data after encoding:")
print(df.head())

FileNotFoundError: [Errno 2] No such file or directory: 'Titanic-Dataset.csv'

In [1]:
import pandas as pd
import numpy as np

d =np.array([1,2,3,4,5])
print(d)
d1=pd.Series(d)
print(d1)

[1 2 3 4 5]
0    1
1    2
2    3
3    4
4    5
dtype: int64


In [2]:
import pandas as pd
import numpy as np

d=pd.read_excel("Demo Data DSBDA.xlsx")
print(d)

          Sr. no.                    Roll No        Name of the Student   DM  \
0               1                     SCOA01              ALISHA SHEIKH   24   
1               2                     SCOA02  SOHAM JAYYANNTH DESHMUKKH   16   
2               3                     SCOA03         SHELAR NEHA NILESH   20   
3               4                     SCOA04                RIYA JAWALE   18   
4               5                     SCOA05      NARHE VARSHA RAOSAHEB   20   
..            ...                        ...                        ...  ...   
77  Maximum marks                        NaN                        NaN   24   
78            NaN                        NaN                        NaN  NaN   
79            NaN                        NaN                        NaN  NaN   
80            NaN                        NaN                        NaN  NaN   
81            NaN  Internal Exam Coordinator                        NaN  NaN   

    FDS  OOP   CG DELD  Unnamed: 8  Unn

In [3]:
d1 = pd.Series(d['DM'])
print(d1)

0      24
1      16
2      20
3      18
4      20
     ... 
77     24
78    NaN
79    NaN
80    NaN
81    NaN
Name: DM, Length: 82, dtype: object


In [4]:
d1 = pd.Series(d['Name of the Student'])
print(d1)

0                 ALISHA SHEIKH
1     SOHAM JAYYANNTH DESHMUKKH
2            SHELAR NEHA NILESH
3                   RIYA JAWALE
4         NARHE VARSHA RAOSAHEB
                ...            
77                          NaN
78                          NaN
79                          NaN
80                          NaN
81                          NaN
Name: Name of the Student, Length: 82, dtype: object


In [5]:
d=df.replace(to_replace = np.NaN, value=0
print(d)

SyntaxError: '(' was never closed (2733813884.py, line 1)

In [6]:
d=df.replace(to_replace = np.NaN, value=0)
print(d)

NameError: name 'df' is not defined

In [7]:
d=d1.replace(to_replace = np.NaN, value=0
print(d)

SyntaxError: '(' was never closed (1956306326.py, line 1)

In [8]:
d=d1.replace(to_replace = np.NaN, value=0)
print(d)

0                 ALISHA SHEIKH
1     SOHAM JAYYANNTH DESHMUKKH
2            SHELAR NEHA NILESH
3                   RIYA JAWALE
4         NARHE VARSHA RAOSAHEB
                ...            
77                            0
78                            0
79                            0
80                            0
81                            0
Name: Name of the Student, Length: 82, dtype: object
